server:
  port: 8081

spring:
  application:
    name: dummy
  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: debug

cloud:
  aws:
    s3:
      bucket: ${bucket}
      base-url: ${url}
    credentials:
      access-key: ${accessKey}
      secret-key: ${secretKey}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
