server:
  port: 9003
spring:
  application:
    name: fridge-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka
